### ISSUE TITLE
Double click items in Missions/Saves lists does not load or save

### ISSUE THREAD

**Issue by LpTrip** [Kromster80/knights_province#211]
Issue is pretty much self explainatory. You can't load or save a game by double clicking on the list. Also, you can't load a map inside Map Editor, when doubleclicking in Menu > Load Map.

**Comment by Kromster80** [comment]
"Mission > Load" - allowed, since player is already okay with loosing mission progress if he got here. If he misclicks a savegame, he can easily reload the right one.

"Mission > Save" - double-click should not be allowed, since player needs to verify he's okay with overwriting old save. Thus there's smaller chance of loosing a savegame by mistake.

"MapEd > Load" - allowed, since player is already okay with loosing MapEd progress if he got here. If he misclicks a map, he can easily reload the right one.

Completed: At revision: 8697
